*********************************************************************** 00000100
* AB  SYSTEM  -            FCT ENTRIES           FOR CICS 1.6         * 00000200
*********************************************************************** 00000300
ABAUD    DFHFCT TYPE=DATASET,                                          X00000400
               DATASET=ABAUD,                                          X00000500
               ACCMETH=(VSAM,KSDS),                                    X00000600
               SERVREQ=(BROWSE,NEWREC,PUT,GET,UPDATE,SHARE,DELETE),    X00000700
               FILSTAT=(ENABLED,CLOSED),                               X00000800
               RECFORM=(FIXED,BLOCKED),                                X00000900
               STRNO=2,                                                X00001000
               BUFND=2,                                                X00001100
               BUFNI=1,                                                X00001200
               JID=NO,                                                 X00001300
               LOG=NO                                                   00001400
ABBCR    DFHFCT TYPE=DATASET,                                          X00001500
               DATASET=ABBCR,                                          X00001600
               ACCMETH=(VSAM,KSDS),                                    X00001700
               SERVREQ=(BROWSE,NEWREC,PUT,GET,UPDATE,SHARE,DELETE),    X00001800
               FILSTAT=(ENABLED,CLOSED),                               X00001900
               STRNO=2,                                                X00002000
               BUFND=2,                                                X00002100
               BUFNI=1,                                                X00002200
               JID=NO,                                                 X00002300
               LOG=NO                                                   00002400
ABRPT    DFHFCT TYPE=DATASET,                                          X00002500
               DATASET=ABRPT,                                          X00002600
               ACCMETH=(VSAM,KSDS),                                    X00002700
               SERVREQ=(BROWSE,NEWREC,PUT,GET,UPDATE,SHARE,DELETE),    X00002800
               FILSTAT=(ENABLED,CLOSED),                               X00002900
               STRNO=2,                                                X00003000
               BUFND=2,                                                X00003100
               BUFNI=1,                                                X00003200
               JID=NO,                                                 X00003300
               LOG=NO                                                   00003400