*********************************************************************** 00000100
*  DA SYSTEM ONLINE FILES - FCT ENTRIES                               * 00000200
*********************************************************************** 00000300
DATBL    DFHFCT TYPE=DATASET,                                          X00000400
               DATASET=DATBL,                                          X00000500
               ACCMETH=(VSAM,KSDS),                                    X00000600
               SERVREQ=(NEWREC,UPDATE,BROWSE,DELETE,SHARE),            X00000700
               FILSTAT=(ENABLED,CLOSED),                               X00000800
               STRNO=1,                                                X00000900
               BUFND=2,                                                X00001000
               BUFNI=2,                                                X00001100
               JID=NO,                                                 X00001200
               LOG=NO                                                   00001300