000100****************************************************************
000200*    OUTPUT FILE HANDLING ROUTINES: DEFAULT ROUTINE = DAFSSQO  *
000300*                                                              *
000400*    REQ'D FIELDS:  DA-LNK-O-OPER                              *
000500*                   DA-LNK-O-ROUT                              *
000600*                   DA-LNK-O-RTNC                              *
000700*                   DA-LNK-O-EDIT                              *
000800****************************************************************
000900 V0010-O-OPEN.
001000     MOVE 'OPEN'                 TO DA-LNK-O-OPER.
001100     GO TO V0099-O-CALL.
001200 V0020-O-WRIT.
001300     MOVE 'WRIT'                 TO DA-LNK-O-OPER.
001400     GO TO V0099-O-CALL.
001500 V0030-O-CLOS.
001600     MOVE 'CLOS'                 TO DA-LNK-O-OPER.
001700     GO TO V0099-O-CALL.
001800 V0040-O-EDIT.
001900     IF DA-LNK-O-EDIT NOT EQUAL SPACES
002000         CALL 'SILINK2' USING       DA-LNK-O-EDIT
002100                                    DA-LINK-AREA.
002200     GO TO V0099-O-EXIT.
002300 V0099-O-CALL.
002400
002500     MOVE 'N'                    TO DA-LNK-O-RTNC.
002600     CALL 'SILINK2'     USING       DA-LNK-O-ROUT
002700                                    DA-LINK-AREA.
002800 V0099-O-EXIT.
002900     EXIT.