*********************************************************************** 00000100
*  DA SYSTEM  - ON-LINE PROGRAMS                 .....PPT ENTRIES.....* 00000200
*********************************************************************** 00000300
         DFHPPT TYPE=ENTRY,PROGRAM=FIDACD,PGMLANG=ASSEMBLER             00000400
         DFHPPT TYPE=ENTRY,PROGRAM=FIDACH,PGMLANG=ASSEMBLER             00000500
         DFHPPT TYPE=ENTRY,PROGRAM=FIDACM,PGMLANG=ASSEMBLER             00000600
         DFHPPT TYPE=ENTRY,PROGRAM=FIDATM,PGMLANG=ASSEMBLER             00000700
         DFHPPT TYPE=ENTRY,PROGRAM=FIDACD01,PGMLANG=COBOL               00011300
         DFHPPT TYPE=ENTRY,PROGRAM=FIDACH01,PGMLANG=COBOL               00011400
         DFHPPT TYPE=ENTRY,PROGRAM=FIDACM01,PGMLANG=COBOL               00011500
         DFHPPT TYPE=ENTRY,PROGRAM=FIDATM01,PGMLANG=COBOL               00011600
*                                                                       00029200