*********************************************************************** 00016000
*FIAS DEALER RESERVE ONLINE FILES - FCT ENTRIES  1.6                  * 00016100
*********************************************************************** 00016200
DRALP    DFHFCT TYPE=DATASET,                                          X00016300
               DATASET=DRALP,                                          X00016400
               ACCMETH=(VSAM,KSDS),                                    X00016500
               SERVREQ=(NEWREC,PUT,UPDATE,BROWSE),                     X00016600
               FILSTAT=(ENABLED,CLOSED),                               X00016700
               STRNO=1,                                                X00016800
               BUFND=2,                                                X00016900
               BUFNI=2,                                                X00017000
               JID=NO,                                                 X00017100
               LOG=NO                                                   00017200
DRMEM    DFHFCT TYPE=DATASET,                                          X00017300
               DATASET=DRMEM,                                          X00017400
               ACCMETH=(VSAM,KSDS),                                    X00017500
               SERVREQ=(NEWREC,PUT,UPDATE,BROWSE),                     X00017600
               FILSTAT=(ENABLED,CLOSED),                               X00017700
               RECFORM=(FIXED,BLOCKED),                                X00017750
               STRNO=1,                                                X00017800
               BUFND=2,                                                X00017900
               BUFNI=2,                                                X00018000
               JID=NO,                                                 X00018100
               LOG=NO                                                   00018200
DRACT    DFHFCT TYPE=DATASET,                                          X00018300
               DATASET=DRACT,                                          X00018400
               ACCMETH=(VSAM,KSDS),                                    X00018500
               SERVREQ=(NEWREC,PUT,UPDATE,BROWSE),                     X00018600
               FILSTAT=(ENABLED,CLOSED),                               X00018700
               STRNO=1,                                                X00018800
               BUFND=2,                                                X00018900
               BUFNI=2,                                                X00019000
               JID=NO,                                                 X00019100
               LOG=NO                                                   00019200