*********************************************************************** 00000100
*FIAS INSTALLMENT CREDIT ONLINE FILES  1.7  FCT                       * 00000200
*********************************************************************** 00000300
ICACC    DFHFCT TYPE=DATASET,                                          X00000400
               DSNAME=NLIC.CICS.MVS.ICACCM.VSAM,                       X00000500
               DATASET=ICACC,                                          X00000600
               ACCMETH=VSAM,DISP=SHR,                                  X00000700
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00000800
               FILSTAT=(ENABLED,CLOSED),                               X00000900
               RECFORM=(FIXED,BLOCKED),                                X00001000
               STRNO=2,                                                X00001100
               BUFND=2,                                                X00001200
               BUFNI=3,                                                X00001300
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00001400
               LOG=YES                                                  00001500
ICALP    DFHFCT TYPE=DATASET,                                          X00001600
               DSNAME=NLIC.CICS.MVS.ICALPM.VSAM,                       X00001700
               DATASET=ICALP,                                          X00001800
               ACCMETH=VSAM,DISP=SHR,                                  X00001900
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00002000
               FILSTAT=(ENABLED,CLOSED),                               X00002100
               RECFORM=(FIXED,BLOCKED),                                X00002200
               STRNO=1,                                                X00002300
               BUFND=2,                                                X00002400
               BUFNI=1,                                                X00002500
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00002600
               LOG=NO                                                   00002700
ICBCR    DFHFCT TYPE=DATASET,                                          X00002800
               DSNAME=NLIC.CICS.MVS.ICBCRM.VSAM,                       X00002900
               DATASET=ICBCR,                                          X00003000
               ACCMETH=VSAM,DISP=SHR,                                  X00003100
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00003200
               FILSTAT=(ENABLED,CLOSED),                               X00003300
               STRNO=1,                                                X00003400
               BUFND=2,                                                X00003500
               BUFNI=1,                                                X00003600
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00003700
               LOG=NO                                                   00003800
ICLKP    DFHFCT TYPE=DATASET,                                          X00003900
               DSNAME=NLIC.CICS.MVS.ICLKPM.VSAM,                       X00004000
               DATASET=ICLKP,                                          X00004100
               ACCMETH=VSAM,DISP=SHR,                                  X00004200
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00004300
               FILSTAT=(ENABLED,CLOSED),                               X00004400
               STRNO=1,                                                X00004500
               BUFND=2,                                                X00004600
               BUFNI=2,                                                X00004700
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00004800
               LOG=NO                                                   00004900
ICACT    DFHFCT TYPE=DATASET,                                          X00005000
               DSNAME=NLIC.CICS.MVS.ICACTM.VSAM,                       X00005100
               DATASET=ICACT,                                          X00005200
               ACCMETH=VSAM,DISP=SHR,                                  X00005300
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00005400
               FILSTAT=(ENABLED,CLOSED),                               X00005500
               STRNO=2,                                                X00005600
               BUFND=2,                                                X00005700
               BUFNI=2,                                                X00005800
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00005900
               LOG=YES                                                  00006000
ICMEM    DFHFCT TYPE=DATASET,                                          X00006100
               DSNAME=NLIC.CICS.MVS.ICMEMM.VSAM,                       X00006200
               DATASET=ICMEM,                                          X00006300
               ACCMETH=VSAM,DISP=SHR,                                  X00006400
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00006500
               FILSTAT=(ENABLED,CLOSED),                               X00006600
               RECFORM=(FIXED,BLOCKED),                                X00006700
               STRNO=2,                                                X00006800
               BUFND=2,                                                X00006900
               BUFNI=3,                                                X00007000
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00007100
               LOG=YES                                                  00007200
ICPRD    DFHFCT TYPE=DATASET,                                          X00007300
               DSNAME=NLIC.CICS.MVS.ICPRDM.VSAM,                       X00007400
               DATASET=ICPRD,                                          X00007500
               ACCMETH=VSAM,DISP=SHR,                                  X00007600
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00007700
               FILSTAT=(ENABLED,CLOSED),                               X00007800
               RECFORM=(FIXED,BLOCKED),                                X00007900
               STRNO=1,                                                X00008000
               BUFND=2,                                                X00008100
               BUFNI=1,                                                X00008200
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00008300
               LOG=NO                                                   00008400