*********************************************************************** 00000100
*  ADVANCED LOANS SYSTEM                      FCT ENTRIES             * 00000200
*********************************************************************** 00000300
AMACT01  DFHFCT TYPE=DATASET,                                          X00000400
               DATASET=AMACT01,                                        X00000500
               DSNAME=NCI.KO.KO.T01.AMACT.VREPRO,                      X00000600
               ACCMETH=VSAM,DISP=SHR,                                  X00000700
               SERVREQ=(ADD,UPDATE,DELETE,BROWSE),                     X00000800
               FILSTAT=(ENABLED,CLOSED),                               X00000900
               RECFORM=(VARIABLE,BLOCKED),                             X00001000
               STRNO=3,                                                X00001100
               BUFND=4,RSL=PUBLIC,                                     X00001200
               BUFNI=5,LSRPOOL=NONE,                                   X00001300
               JID=NO,                                                 X00001400
               LOG=YES                                                  00001500
*********************************************************************** 00001600
* COMMERCIAL LOAN SYSTEM - ON-LINE FILES CICS 1.7  ....FCT ENTRIES....* 00001700
*********************************************************************** 00001800
*****                                                                   00001900
* COMMERCIAL LOANS  NOTE SYSTEM                                         00002000
*****                                                                   00002100
CLMEM01  DFHFCT TYPE=DATASET,                                          X00002200
               DSNAME=NCI.KO.KO.T01.CLMEMM.VREPRO,                     X00002300
               DATASET=CLMEM01,                                        X00002400
               ACCMETH=VSAM,DISP=SHR,                                  X00002500
               SERVREQ=(ADD,UPDATE,BROWSE),                            X00002600
               FILSTAT=(ENABLED,CLOSED),                               X00002700
               RECFORM=(FIXED,BLOCKED),                                X00002800
               STRNO=1,                                                X00002900
               BUFND=2,                                                X00003000
               BUFNI=3,                                                X00003100
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00003200
               LOG=NO                                                   00003300
*********************************************************************** 00003400
*FIAS INSTALLMENT CREDIT ONLINE FILES  1.7  FCT                       * 00003500
*********************************************************************** 00003600
ICMEM01  DFHFCT TYPE=DATASET,                                          X00003700
               DSNAME=NCI.KO.KO.T01.ICMEMM.VREPRO,                     X00003800
               DATASET=ICMEM01,                                        X00003900
               ACCMETH=VSAM,DISP=SHR,                                  X00004000
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00004100
               FILSTAT=(ENABLED,CLOSED),                               X00004200
               RECFORM=(FIXED,BLOCKED),                                X00004300
               STRNO=2,                                                X00004400
               BUFND=2,                                                X00004500
               BUFNI=3,                                                X00004600
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00004700
               LOG=YES                                                  00004800
*********************************************************************** 00004900
*  IM SYSTEM ONLINE FILES                                             * 00005000
*********************************************************************** 00005100
IMMEM01  DFHFCT TYPE=DATASET,                                          X00005200
               DSNAME=NCI.KO.KO.T01.IMMEMM.VREPRO,                     X00005300
               DATASET=IMMEM01,                                        X00005400
               ACCMETH=VSAM,DISP=SHR,                                  X00005500
               SERVREQ=(READ,UPDATE,ADD,BROWSE,DELETE),                X00005600
               FILSTAT=(ENABLED,CLOSED),                               X00005700
               RECFORM=(FIXED,BLOCKED),                                X00005800
               STRNO=2,                                                X00005900
               BUFND=3,                                                X00006000
               BUFNI=2,                                                X00006100
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00006200
               LOG=YES                                                  00006300
*********************************************************************** 00006400
*REAL ESTATE SYSTEM      FIAS ON-LINE FILES                           * 00006500
*********************************************************************** 00006600
REMEM01  DFHFCT TYPE=DATASET,                                  2305749 X00006700
               DSNAME=NCI.KO.KO.T01.REMEMM.VREPRO,                     X00006800
               DATASET=REMEM01,                                2305749 X00006900
               ACCMETH=VSAM,DISP=SHR,                                  X00007000
               SERVREQ=(READ,UPDATE,ADD,BROWSE),                       X00007100
               FILSTAT=(ENABLED,CLOSED),                               X00007200
               RECFORM=(FIXED,BLOCKED),                                X00007300
               STRNO=2,                                                X00007400
               BUFND=2,                                                X00007500
               BUFNI=2,                                                X00007600
               JID=NO,LSRPOOL=1,RSL=PUBLIC,                            X00007700
               LOG=YES                                                  00007800