***   III.  FCT ENTRIES                                                 00001000
*                                                                       00002000
* ********************************************************************* 00003000
*   EXCHANGE RATE FILE FCT ENTRIES                                    * 00004000
* ********************************************************************* 00005000
*                                                                       00006000
NXXRC    DFHFCT TYPE=DATASET,                                          X00007000
               DSNAME=NCI.NX.OL.T00.NXXRCM.VREPRO,                     X00008000
               DATASET=NXXRC,                                          X00009000
               ACCMETH=VSAM,                                           X00010000
               DISP=SHR,                                               X00011000
               SERVREQ=(ADD,READ,UPDATE,DELETE,BROWSE),                X00012000
               FILSTAT=(ENABLED,CLOSED),                               X00013000
               STRNO=1,                                                X00014000
               JID=NO,                                                 X00015000
               LSRPOOL=1,                                              X00016000
               RSL=PUBLIC,                                             X00017000
               LOG=NO                                                   00018000
*                                                                       00019000
* ********************************************************************* 00020000
*   EXCHANGE RATE FILE FCT ENTRIES                                    * 00021000
* ********************************************************************* 00022000
*                                                                       00023000
NXXRT    DFHFCT TYPE=DATASET,                                          X00024000
               DSNAME=NCI.NX.OL.T00.NXXRTM.VREPRO,                     X00025000
               DATASET=NXXRT,                                          X00026000
               ACCMETH=VSAM,                                           X00027000
               DISP=SHR,                                               X00028000
               SERVREQ=(ADD,READ,UPDATE,DELETE,BROWSE),                X00029000
               FILSTAT=(ENABLED,CLOSED),                               X00030000
               STRNO=1,                                                X00031000
               JID=NO,                                                 X00032000
               LSRPOOL=1,                                              X00033000
               RSL=PUBLIC,                                             X00034000
               LOG=NO                                                   00035000